# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dummy-torch',
                'doc_host': 'https://khannay.github.io',
                'git_url': 'https://github.com/khannay/dummy-torch',
                'lib_path': 'dummy_torch'},
  'syms': {'dummy_torch.core': {'dummy_torch.core.foo': ('core.html#foo', 'dummy_torch/core.py')}}}
